import React, { useState } from 'react';
import { Download, FileText, BarChart3, Calendar, Filter, Printer } from 'lucide-react';
import { format } from 'date-fns';
import { LoadingSpinner } from '../UI/LoadingSpinner';
import { useApp } from '../../context/AppContext';

export const Reports: React.FC = () => {
  const { goats, caretakers, expenses, healthRecords, loading, error } = useApp();
  const [selectedReport, setSelectedReport] = useState('inventory');
  const [dateRange, setDateRange] = useState('month');
  const [isExporting, setIsExporting] = useState(false);

  const exportToPDF = async () => {
    setIsExporting(true);
    try {
      // Simulate PDF generation
      await new Promise(resolve => setTimeout(resolve, 2000));
      
      // Create a simple text-based report for download
      const reportData = generateReportData();
      const blob = new Blob([reportData], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `livestock-report-${selectedReport}-${format(new Date(), 'yyyy-MM-dd')}.txt`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    } catch (error) {
      console.error('Export failed:', error);
    } finally {
      setIsExporting(false);
    }
  };

  const generateReportData = () => {
    const inventoryReport = generateInventoryReport();
    const financialReport = generateFinancialReport();
    const totalExpenses = expenses.reduce((sum, expense) => sum + expense.amount, 0) + 
                         healthRecords.reduce((sum, record) => sum + record.cost, 0);
    
    return `
LIVESTOCK MANAGEMENT REPORT
Generated on: ${format(new Date(), 'MMMM dd, yyyy')}
Report Type: ${selectedReport.toUpperCase()}

========================================

SUMMARY:
- Total Goats: ${inventoryReport.summary.totalGoats}
- Active Goats: ${inventoryReport.summary.activeGoats}
- Sold Goats: ${inventoryReport.summary.soldGoats}
- Total Investment: ₹${inventoryReport.summary.totalValue.toLocaleString()}
- Total Expenses: ₹${totalExpenses.toLocaleString()}
- Total Revenue: ₹${financialReport.summary.totalRevenue.toLocaleString()}
- Net Profit: ₹${financialReport.summary.netProfit.toLocaleString()}

DETAILED INVENTORY:
${goats.map(goat => 
  `${goat.tagNumber} - ${goat.nickname || 'Unnamed'} (${goat.breed}, ${goat.gender}, ${goat.currentWeight}kg, ${goat.status})`
).join('\n')}

EXPENSE BREAKDOWN:
${expenses.map(expense => 
  `${expense.date.toISOString().split('T')[0]} - ${expense.category}: ₹${expense.amount} - ${expense.description}`
).join('\n')}

HEALTH EXPENSES:
${healthRecords.map(record => 
  `${record.date.toISOString().split('T')[0]} - ${record.type}: ₹${record.cost} - ${record.description}`
).join('\n')}

========================================
Generated by LivestockPro Management System
    `;
  };

  if (loading) {
    return <LoadingSpinner />;
  }

  if (error) {
    return (
      <div className="space-y-6">
        <div className="bg-red-50 border border-red-200 rounded-lg p-4">
          <p className="text-red-700">Error loading reports: {error}</p>
        </div>
      </div>
    );
  }

  const reportTypes = [
    { id: 'inventory', name: 'Inventory Report', description: 'Complete livestock inventory with current status' },
    { id: 'financial', name: 'Financial Summary', description: 'Revenue, expenses, and profit analysis' },
    { id: 'caretaker', name: 'Caretaker Performance', description: 'Caretaker assignments and earnings' },
    { id: 'health', name: 'Health Summary', description: 'Health records and upcoming treatments' }
  ];

  const formatCurrency = (amount: number) => {
    return new Intl.NumberFormat('en-PK', {
      style: 'currency',
      currency: 'PKR',
      minimumFractionDigits: 0
    }).format(amount);
  };

  const generateInventoryReport = () => {
    const totalGoats = goats.length;
    const activeGoats = goats.filter(g => g.status === 'Active').length;
    const soldGoats = goats.filter(g => g.status === 'Sold').length;
    const breedBreakdown = goats.reduce((acc, goat) => {
      acc[goat.breed] = (acc[goat.breed] || 0) + 1;
      return acc;
    }, {} as Record<string, number>);

    return {
      summary: {
        totalGoats,
        activeGoats,
        soldGoats,
        totalValue: goats.reduce((sum, goat) => sum + goat.purchasePrice, 0)
      },
      breeds: breedBreakdown,
      goats: goats
    };
  };

  const generateFinancialReport = () => {
    const totalInvestment = goats.reduce((sum, goat) => sum + goat.purchasePrice, 0);
    const totalRevenue = goats
      .filter(g => g.salePrice)
      .reduce((sum, goat) => sum + (goat.salePrice || 0), 0);
    const totalExpenses = expenses.reduce((sum, expense) => sum + expense.amount, 0);
    const netProfit = totalRevenue - totalInvestment - totalExpenses;

    return {
      summary: {
        totalInvestment,
        totalRevenue,
        totalExpenses,
        netProfit,
        profitMargin: totalRevenue > 0 ? ((netProfit / totalRevenue) * 100) : 0
      },
      expenses: expenses,
      sales: goats.filter(g => g.status === 'Sold')
    };
  };

  const inventoryReport = generateInventoryReport();
  const financialReport = generateFinancialReport();

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <div>
          <h2 className="text-2xl font-bold text-gray-900">Reports & Analytics</h2>
          <p className="text-gray-600">Generate comprehensive reports for your livestock business</p>
        </div>
        <div className="flex space-x-2">
          <select
            value={dateRange}
            onChange={(e) => setDateRange(e.target.value)}
            className="border border-gray-300 rounded-lg px-3 py-2 focus:ring-2 focus:ring-emerald-500 focus:border-emerald-500"
          >
            <option value="week">This Week</option>
            <option value="month">This Month</option>
            <option value="quarter">This Quarter</option>
            <option value="year">This Year</option>
          </select>
          <button 
            onClick={exportToPDF}
            disabled={isExporting}
            className="flex items-center px-4 py-2 bg-emerald-600 text-white rounded-lg hover:bg-emerald-700 transition-colors disabled:opacity-50"
          >
            <Download className="h-5 w-5 mr-2" />
            {isExporting ? 'Exporting...' : 'Export Report'}
          </button>
          <button className="flex items-center px-4 py-2 border border-gray-300 text-gray-700 rounded-lg hover:bg-gray-50 transition-colors">
            <Printer className="h-5 w-5 mr-2" />
            Print
          </button>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        {reportTypes.map((report) => (
          <button
            key={report.id}
            onClick={() => setSelectedReport(report.id)}
            className={`text-left p-4 rounded-lg border-2 transition-all ${
              selectedReport === report.id
                ? 'border-emerald-500 bg-emerald-50'
                : 'border-gray-200 hover:border-gray-300 bg-white'
            }`}
          >
            <div className="flex items-center mb-2">
              <FileText className={`h-5 w-5 mr-2 ${
                selectedReport === report.id ? 'text-emerald-600' : 'text-gray-400'
              }`} />
              <h3 className={`font-medium ${
                selectedReport === report.id ? 'text-emerald-900' : 'text-gray-900'
              }`}>
                {report.name}
              </h3>
            </div>
            <p className={`text-sm ${
              selectedReport === report.id ? 'text-emerald-700' : 'text-gray-600'
            }`}>
              {report.description}
            </p>
          </button>
        ))}
      </div>

      <div className="bg-white rounded-lg shadow-sm border border-gray-200">
        {selectedReport === 'inventory' && (
          <div className="p-6">
            <div className="flex items-center justify-between mb-6">
              <h3 className="text-xl font-semibold text-gray-900">Inventory Report</h3>
              <span className="text-sm text-gray-500">Generated on {format(new Date(), 'MMM dd, yyyy')}</span>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-4 gap-4 mb-6">
              <div className="bg-blue-50 rounded-lg p-4">
                <p className="text-sm text-blue-600">Total Goats</p>
                <p className="text-2xl font-bold text-blue-900">{inventoryReport.summary.totalGoats}</p>
              </div>
              <div className="bg-emerald-50 rounded-lg p-4">
                <p className="text-sm text-emerald-600">Active</p>
                <p className="text-2xl font-bold text-emerald-900">{inventoryReport.summary.activeGoats}</p>
              </div>
              <div className="bg-purple-50 rounded-lg p-4">
                <p className="text-sm text-purple-600">Sold</p>
                <p className="text-2xl font-bold text-purple-900">{inventoryReport.summary.soldGoats}</p>
              </div>
              <div className="bg-yellow-50 rounded-lg p-4">
                <p className="text-sm text-yellow-600">Total Value</p>
                <p className="text-2xl font-bold text-yellow-900">{formatCurrency(inventoryReport.summary.totalValue)}</p>
              </div>
            </div>

            <div className="mb-6">
              <h4 className="font-medium text-gray-900 mb-3">Breed Distribution</h4>
              <div className="grid grid-cols-2 md:grid-cols-4 gap-2">
                {Object.entries(inventoryReport.breeds).map(([breed, count]) => (
                  <div key={breed} className="bg-gray-50 rounded p-3 text-center">
                    <p className="text-sm text-gray-600">{breed}</p>
                    <p className="text-lg font-semibold text-gray-900">{count}</p>
                  </div>
                ))}
              </div>
            </div>

            <div>
              <h4 className="font-medium text-gray-900 mb-3">Detailed Inventory</h4>
              <div className="overflow-x-auto">
                <table className="min-w-full divide-y divide-gray-200">
                  <thead className="bg-gray-50">
                    <tr>
                      <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Tag #</th>
                      <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Name</th>
                      <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Breed</th>
                      <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Status</th>
                      <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Weight</th>
                      <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Value</th>
                    </tr>
                  </thead>
                  <tbody className="bg-white divide-y divide-gray-200">
                    {inventoryReport.goats.map((goat) => (
                      <tr key={goat.id}>
                        <td className="px-4 py-3 text-sm font-medium text-gray-900">{goat.tagNumber}</td>
                        <td className="px-4 py-3 text-sm text-gray-600">{goat.nickname || 'Unnamed'}</td>
                        <td className="px-4 py-3 text-sm text-gray-600">{goat.breed}</td>
                        <td className="px-4 py-3 text-sm">
                          <span className={`px-2 py-1 text-xs font-medium rounded-full ${
                            goat.status === 'Active' ? 'bg-emerald-100 text-emerald-800' :
                            goat.status === 'Sold' ? 'bg-blue-100 text-blue-800' :
                            'bg-gray-100 text-gray-800'
                          }`}>
                            {goat.status}
                          </span>
                        </td>
                        <td className="px-4 py-3 text-sm text-gray-600">{goat.currentWeight}kg</td>
                        <td className="px-4 py-3 text-sm text-gray-900">{formatCurrency(goat.purchasePrice)}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        )}

        {selectedReport === 'financial' && (
          <div className="p-6">
            <div className="flex items-center justify-between mb-6">
              <h3 className="text-xl font-semibold text-gray-900">Financial Summary</h3>
              <span className="text-sm text-gray-500">Generated on {format(new Date(), 'MMM dd, yyyy')}</span>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-4 gap-4 mb-6">
              <div className="bg-purple-50 rounded-lg p-4">
                <p className="text-sm text-purple-600">Total Investment</p>
                <p className="text-2xl font-bold text-purple-900">{formatCurrency(financialReport.summary.totalInvestment)}</p>
              </div>
              <div className="bg-emerald-50 rounded-lg p-4">
                <p className="text-sm text-emerald-600">Total Revenue</p>
                <p className="text-2xl font-bold text-emerald-900">{formatCurrency(financialReport.summary.totalRevenue)}</p>
              </div>
              <div className="bg-red-50 rounded-lg p-4">
                <p className="text-sm text-red-600">Total Expenses</p>
                <p className="text-2xl font-bold text-red-900">{formatCurrency(financialReport.summary.totalExpenses)}</p>
              </div>
              <div className={`rounded-lg p-4 ${
                financialReport.summary.netProfit >= 0 ? 'bg-emerald-50' : 'bg-red-50'
              }`}>
                <p className={`text-sm ${
                  financialReport.summary.netProfit >= 0 ? 'text-emerald-600' : 'text-red-600'
                }`}>Net Profit</p>
                <p className={`text-2xl font-bold ${
                  financialReport.summary.netProfit >= 0 ? 'text-emerald-900' : 'text-red-900'
                }`}>{formatCurrency(financialReport.summary.netProfit)}</p>
              </div>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
              <div>
                <h4 className="font-medium text-gray-900 mb-3">Recent Sales</h4>
                <div className="space-y-3">
                  {financialReport.sales.map((goat) => (
                    <div key={goat.id} className="flex justify-between items-center bg-gray-50 rounded p-3">
                      <div>
                        <p className="font-medium text-gray-900">{goat.tagNumber} - {goat.nickname}</p>
                        <p className="text-sm text-gray-600">{goat.saleDate && format(goat.saleDate, 'MMM dd, yyyy')}</p>
                      </div>
                      <div className="text-right">
                        <p className="font-medium text-emerald-600">{formatCurrency(goat.salePrice || 0)}</p>
                        <p className="text-sm text-gray-600">
                          +{formatCurrency((goat.salePrice || 0) - goat.purchasePrice)}
                        </p>
                      </div>
                    </div>
                  ))}
                </div>
              </div>

              <div>
                <h4 className="font-medium text-gray-900 mb-3">Recent Expenses</h4>
                <div className="space-y-3">
                  {financialReport.expenses.map((expense) => (
                    <div key={expense.id} className="flex justify-between items-center bg-gray-50 rounded p-3">
                      <div>
                        <p className="font-medium text-gray-900">{expense.description}</p>
                        <p className="text-sm text-gray-600">{expense.category} • {format(expense.date, 'MMM dd, yyyy')}</p>
                      </div>
                      <p className="font-medium text-red-600">-{formatCurrency(expense.amount)}</p>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </div>
        )}

        {selectedReport === 'caretaker' && (
          <div className="p-6">
            <div className="flex items-center justify-between mb-6">
              <h3 className="text-xl font-semibold text-gray-900">Caretaker Performance</h3>
              <span className="text-sm text-gray-500">Generated on {format(new Date(), 'MMM dd, yyyy')}</span>
            </div>

            <div className="space-y-4">
              {caretakers.map((caretaker) => {
                const assignedGoats = goats.filter(g => g.caretakerId === caretaker.id);
                const activeGoats = assignedGoats.filter(g => g.status === 'Active');
                const soldGoats = assignedGoats.filter(g => g.status === 'Sold');
                
                return (
                  <div key={caretaker.id} className="border border-gray-200 rounded-lg p-4">
                    <div className="flex justify-between items-start mb-4">
                      <div>
                        <h4 className="font-semibold text-gray-900">{caretaker.name}</h4>
                        <p className="text-sm text-gray-600">{caretaker.contactInfo.address}</p>
                      </div>
                      <div className="text-right">
                        <p className="font-medium text-emerald-600">{formatCurrency(caretaker.totalEarnings)}</p>
                        <p className="text-sm text-gray-600">Total Earnings</p>
                      </div>
                    </div>
                    
                    <div className="grid grid-cols-3 gap-4">
                      <div className="text-center">
                        <p className="text-2xl font-bold text-blue-600">{assignedGoats.length}</p>
                        <p className="text-sm text-gray-600">Total Assigned</p>
                      </div>
                      <div className="text-center">
                        <p className="text-2xl font-bold text-emerald-600">{activeGoats.length}</p>
                        <p className="text-sm text-gray-600">Active</p>
                      </div>
                      <div className="text-center">
                        <p className="text-2xl font-bold text-purple-600">{soldGoats.length}</p>
                        <p className="text-sm text-gray-600">Sold</p>
                      </div>
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
        )}

        {selectedReport === 'health' && (
          <div className="p-6">
            <div className="flex items-center justify-between mb-6">
              <h3 className="text-xl font-semibold text-gray-900">Health Summary</h3>
              <span className="text-sm text-gray-500">Generated on {format(new Date(), 'MMM dd, yyyy')}</span>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6">
              <div className="bg-emerald-50 rounded-lg p-4">
                <p className="text-sm text-emerald-600">Healthy</p>
                <p className="text-2xl font-bold text-emerald-900">
                  {goats.filter(g => g.status === 'Active').length}
                </p>
              </div>
              <div className="bg-yellow-50 rounded-lg p-4">
                <p className="text-sm text-yellow-600">Under Treatment</p>
                <p className="text-2xl font-bold text-yellow-900">0</p>
              </div>
              <div className="bg-blue-50 rounded-lg p-4">
                <p className="text-sm text-blue-600">Recovered</p>
                <p className="text-2xl font-bold text-blue-900">1</p>
              </div>
            </div>

            <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-4">
              <h4 className="font-medium text-yellow-900 mb-3">Upcoming Treatments</h4>
              <div className="space-y-2">
                <div className="flex justify-between items-center">
                  <span className="text-yellow-800">GT001 - PPR Vaccination Due</span>
                  <span className="text-yellow-600 font-medium">Feb 01, 2025</span>
                </div>
                <div className="flex justify-between items-center">
                  <span className="text-yellow-800">GT001 - Deworming Due</span>
                  <span className="text-yellow-600 font-medium">Jan 15, 2025</span>
                </div>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};